// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hbase.proto

package im.pt.message.proto;

public interface ForwardUserMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messagedbold.ForwardUserMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 消息发送者
   * </pre>
   *
   * <code>int32 FromId = 1;</code>
   */
  int getFromId();

  /**
   * <pre>
   * 消息是否加密
   * </pre>
   *
   * <code>int32 Encry = 2;</code>
   */
  int getEncry();

  /**
   * <pre>
   * 图片组ID
   * </pre>
   *
   * <code>int64 GroupId = 3;</code>
   */
  long getGroupId();

  /**
   * <pre>
   * 消息ID
   * </pre>
   *
   * <code>int32 MsgID = 4;</code>
   */
  int getMsgID();

  /**
   * <pre>
   * 媒体类型
   * </pre>
   *
   * <code>int32 Media = 5;</code>
   */
  int getMedia();

  /**
   * <pre>
   * 时间戳
   * </pre>
   *
   * <code>int32 Date = 6;</code>
   */
  int getDate();

  /**
   * <pre>
   * 机器人ID
   * </pre>
   *
   * <code>int32 ViaBotID = 7;</code>
   */
  int getViaBotID();

  /**
   * <pre>
   * 消息
   * </pre>
   *
   * <code>string Message = 8;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 消息
   * </pre>
   *
   * <code>string Message = 8;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * 媒体信息摘要
   * </pre>
   *
   * <code>bytes MediaData = 9;</code>
   */
  com.google.protobuf.ByteString getMediaData();

  /**
   * <pre>
   * 键盘信息
   * </pre>
   *
   * <code>bytes ReplyMarkup = 10;</code>
   */
  com.google.protobuf.ByteString getReplyMarkup();

  /**
   * <pre>
   * 转发摘要
   * </pre>
   *
   * <code>bytes FwdFrom = 11;</code>
   */
  com.google.protobuf.ByteString getFwdFrom();

  /**
   * <pre>
   * 高亮信息
   * </pre>
   *
   * <code>repeated bytes Entities = 12;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getEntitiesList();
  /**
   * <pre>
   * 高亮信息
   * </pre>
   *
   * <code>repeated bytes Entities = 12;</code>
   */
  int getEntitiesCount();
  /**
   * <pre>
   * 高亮信息
   * </pre>
   *
   * <code>repeated bytes Entities = 12;</code>
   */
  com.google.protobuf.ByteString getEntities(int index);
}
