// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hbase.proto

package im.pt.message.proto;

public interface GetUserMsgUUIDRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messagedbold.GetUserMsgUUIDResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 UUID = 1;</code>
   */
  long getUUID();

  /**
   * <code>int32 WithID = 2;</code>
   */
  int getWithID();
}
