// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hbase.proto

package im.pt.message.proto;

public interface GetUserMsgByUserIDMsgIDsReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messagedbold.GetUserMsgByUserIDMsgIDsReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 UserID = 1;</code>
   */
  int getUserID();

  /**
   * <code>int32 WithID = 2;</code>
   */
  int getWithID();

  /**
   * <code>int32 WithType = 3;</code>
   */
  int getWithType();

  /**
   * <code>repeated int32 MsgIDs = 4;</code>
   */
  java.util.List<java.lang.Integer> getMsgIDsList();
  /**
   * <code>repeated int32 MsgIDs = 4;</code>
   */
  int getMsgIDsCount();
  /**
   * <code>repeated int32 MsgIDs = 4;</code>
   */
  int getMsgIDs(int index);

  /**
   * <pre>
   * 数据库类型
   * </pre>
   *
   * <code>.messagedbold.DATABASETYPE DType = 5;</code>
   */
  int getDTypeValue();
  /**
   * <pre>
   * 数据库类型
   * </pre>
   *
   * <code>.messagedbold.DATABASETYPE DType = 5;</code>
   */
  im.pt.message.proto.DATABASETYPE getDType();
}
