// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hbase.proto

package im.pt.message.proto;

public interface GetUserMsgIdByUUIDRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messagedbold.GetUserMsgIdByUUIDResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 WithID = 1;</code>
   */
  int getWithID();

  /**
   * <code>int32 MsgID = 2;</code>
   */
  int getMsgID();
}
