//src目录执行
//protoc --gogofast_out=plugins=grpc:. gitlab.chatserver.im/interfaceprobuf/photoresize/photoresize.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: photoresize.proto

package photocropping

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_OK          ErrCode = 0 // 成功
	ErrCode_ResizeFail  ErrCode = 1 //失败
	ErrCode_NotModified ErrCode = 2 //未修改
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0: "OK",
		1: "ResizeFail",
		2: "NotModified",
	}
	ErrCode_value = map[string]int32{
		"OK":          0,
		"ResizeFail":  1,
		"NotModified": 2,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_photoresize_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_photoresize_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_photoresize_proto_rawDescGZIP(), []int{0}
}

type ResizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ResizeRequest) Reset() {
	*x = ResizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_photoresize_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeRequest) ProtoMessage() {}

func (x *ResizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_photoresize_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeRequest.ProtoReflect.Descriptor instead.
func (*ResizeRequest) Descriptor() ([]byte, []int) {
	return file_photoresize_proto_rawDescGZIP(), []int{0}
}

func (x *ResizeRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResizeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error  ErrCode      `protobuf:"varint,1,opt,name=error,proto3,enum=photocropping.ErrCode" json:"error,omitempty"` //
	Msg    string       `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Photos []*PhotoSize `protobuf:"bytes,3,rep,name=photos,proto3" json:"photos,omitempty"`
	W      int32        `protobuf:"varint,4,opt,name=w,proto3" json:"w,omitempty"` //原始宽
	H      int32        `protobuf:"varint,5,opt,name=h,proto3" json:"h,omitempty"` //原始高
}

func (x *ResizeReply) Reset() {
	*x = ResizeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_photoresize_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResizeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeReply) ProtoMessage() {}

func (x *ResizeReply) ProtoReflect() protoreflect.Message {
	mi := &file_photoresize_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeReply.ProtoReflect.Descriptor instead.
func (*ResizeReply) Descriptor() ([]byte, []int) {
	return file_photoresize_proto_rawDescGZIP(), []int{1}
}

func (x *ResizeReply) GetError() ErrCode {
	if x != nil {
		return x.Error
	}
	return ErrCode_OK
}

func (x *ResizeReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ResizeReply) GetPhotos() []*PhotoSize {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *ResizeReply) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *ResizeReply) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

type PhotoSize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Weight int32  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Height int32  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Data   []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PhotoSize) Reset() {
	*x = PhotoSize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_photoresize_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhotoSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoSize) ProtoMessage() {}

func (x *PhotoSize) ProtoReflect() protoreflect.Message {
	mi := &file_photoresize_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoSize.ProtoReflect.Descriptor instead.
func (*PhotoSize) Descriptor() ([]byte, []int) {
	return file_photoresize_proto_rawDescGZIP(), []int{2}
}

func (x *PhotoSize) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PhotoSize) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *PhotoSize) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PhotoSize) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResizeMediaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ResizeMediaRequest) Reset() {
	*x = ResizeMediaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_photoresize_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResizeMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeMediaRequest) ProtoMessage() {}

func (x *ResizeMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_photoresize_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeMediaRequest.ProtoReflect.Descriptor instead.
func (*ResizeMediaRequest) Descriptor() ([]byte, []int) {
	return file_photoresize_proto_rawDescGZIP(), []int{3}
}

func (x *ResizeMediaRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResizeMediaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error  ErrCode      `protobuf:"varint,1,opt,name=error,proto3,enum=photocropping.ErrCode" json:"error,omitempty"`
	Msg    string       `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Photos []*PhotoSize `protobuf:"bytes,3,rep,name=photos,proto3" json:"photos,omitempty"`
	W      int32        `protobuf:"varint,4,opt,name=w,proto3" json:"w,omitempty"` //原始宽
	H      int32        `protobuf:"varint,5,opt,name=h,proto3" json:"h,omitempty"` //原始高
}

func (x *ResizeMediaReply) Reset() {
	*x = ResizeMediaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_photoresize_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResizeMediaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeMediaReply) ProtoMessage() {}

func (x *ResizeMediaReply) ProtoReflect() protoreflect.Message {
	mi := &file_photoresize_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeMediaReply.ProtoReflect.Descriptor instead.
func (*ResizeMediaReply) Descriptor() ([]byte, []int) {
	return file_photoresize_proto_rawDescGZIP(), []int{4}
}

func (x *ResizeMediaReply) GetError() ErrCode {
	if x != nil {
		return x.Error
	}
	return ErrCode_OK
}

func (x *ResizeMediaReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ResizeMediaReply) GetPhotos() []*PhotoSize {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *ResizeMediaReply) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *ResizeMediaReply) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

var File_photoresize_proto protoreflect.FileDescriptor

var file_photoresize_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x63, 0x72, 0x6f, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x22, 0x23, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x9b, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x69,
	0x7a, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x63, 0x72,
	0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x30, 0x0a, 0x06, 0x70, 0x68, 0x6f, 0x74, 0x6f,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x63,
	0x72, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x53, 0x69, 0x7a,
	0x65, 0x52, 0x06, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x77, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x77, 0x12, 0x0c, 0x0a, 0x01, 0x68, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x01, 0x68, 0x22, 0x63, 0x0a, 0x09, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x28, 0x0a, 0x12, 0x52, 0x65,
	0x73, 0x69, 0x7a, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0xa0, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f,
	0x63, 0x72, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x30, 0x0a, 0x06, 0x70, 0x68, 0x6f,
	0x74, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x68, 0x6f, 0x74,
	0x6f, 0x63, 0x72, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x53,
	0x69, 0x7a, 0x65, 0x52, 0x06, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x77,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x77, 0x12, 0x0c, 0x0a, 0x01, 0x68, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x68, 0x2a, 0x32, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x65,
	0x73, 0x69, 0x7a, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x6f,
	0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x10, 0x02, 0x32, 0xa8, 0x01, 0x0a, 0x0b,
	0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x44, 0x0a, 0x06, 0x52,
	0x65, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x63, 0x72, 0x6f,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x63, 0x72, 0x6f, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x53, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x12, 0x21, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x63, 0x72, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x2e, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x63, 0x72, 0x6f, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x1f, 0x5a, 0x1d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x70, 0x72, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x63,
	0x72, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_photoresize_proto_rawDescOnce sync.Once
	file_photoresize_proto_rawDescData = file_photoresize_proto_rawDesc
)

func file_photoresize_proto_rawDescGZIP() []byte {
	file_photoresize_proto_rawDescOnce.Do(func() {
		file_photoresize_proto_rawDescData = protoimpl.X.CompressGZIP(file_photoresize_proto_rawDescData)
	})
	return file_photoresize_proto_rawDescData
}

var file_photoresize_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_photoresize_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_photoresize_proto_goTypes = []interface{}{
	(ErrCode)(0),               // 0: photocropping.ErrCode
	(*ResizeRequest)(nil),      // 1: photocropping.ResizeRequest
	(*ResizeReply)(nil),        // 2: photocropping.ResizeReply
	(*PhotoSize)(nil),          // 3: photocropping.PhotoSize
	(*ResizeMediaRequest)(nil), // 4: photocropping.ResizeMediaRequest
	(*ResizeMediaReply)(nil),   // 5: photocropping.ResizeMediaReply
}
var file_photoresize_proto_depIdxs = []int32{
	0, // 0: photocropping.ResizeReply.error:type_name -> photocropping.ErrCode
	3, // 1: photocropping.ResizeReply.photos:type_name -> photocropping.PhotoSize
	0, // 2: photocropping.ResizeMediaReply.error:type_name -> photocropping.ErrCode
	3, // 3: photocropping.ResizeMediaReply.photos:type_name -> photocropping.PhotoSize
	1, // 4: photocropping.PhotoResize.Resize:input_type -> photocropping.ResizeRequest
	4, // 5: photocropping.PhotoResize.ResizeMedia:input_type -> photocropping.ResizeMediaRequest
	2, // 6: photocropping.PhotoResize.Resize:output_type -> photocropping.ResizeReply
	5, // 7: photocropping.PhotoResize.ResizeMedia:output_type -> photocropping.ResizeMediaReply
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_photoresize_proto_init() }
func file_photoresize_proto_init() {
	if File_photoresize_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_photoresize_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_photoresize_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResizeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_photoresize_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhotoSize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_photoresize_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResizeMediaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_photoresize_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResizeMediaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_photoresize_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_photoresize_proto_goTypes,
		DependencyIndexes: file_photoresize_proto_depIdxs,
		EnumInfos:         file_photoresize_proto_enumTypes,
		MessageInfos:      file_photoresize_proto_msgTypes,
	}.Build()
	File_photoresize_proto = out.File
	file_photoresize_proto_rawDesc = nil
	file_photoresize_proto_goTypes = nil
	file_photoresize_proto_depIdxs = nil
}
