// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: imdigsessionserver.proto

package imdigsessionserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImDigSessionServiceClient is the client API for ImDigSessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImDigSessionServiceClient interface {
	// 获取token
	GetToken(ctx context.Context, in *ReqGetTokenMsg, opts ...grpc.CallOption) (*GetTokenReply, error)
	GetUserToken(ctx context.Context, in *ReqGetUserToken, opts ...grpc.CallOption) (*GetUserTokenReply, error)
}

type imDigSessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImDigSessionServiceClient(cc grpc.ClientConnInterface) ImDigSessionServiceClient {
	return &imDigSessionServiceClient{cc}
}

func (c *imDigSessionServiceClient) GetToken(ctx context.Context, in *ReqGetTokenMsg, opts ...grpc.CallOption) (*GetTokenReply, error) {
	out := new(GetTokenReply)
	err := c.cc.Invoke(ctx, "/imdigsessionserver.ImDigSessionService/GetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imDigSessionServiceClient) GetUserToken(ctx context.Context, in *ReqGetUserToken, opts ...grpc.CallOption) (*GetUserTokenReply, error) {
	out := new(GetUserTokenReply)
	err := c.cc.Invoke(ctx, "/imdigsessionserver.ImDigSessionService/GetUserToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImDigSessionServiceServer is the server API for ImDigSessionService service.
// All implementations must embed UnimplementedImDigSessionServiceServer
// for forward compatibility
type ImDigSessionServiceServer interface {
	// 获取token
	GetToken(context.Context, *ReqGetTokenMsg) (*GetTokenReply, error)
	GetUserToken(context.Context, *ReqGetUserToken) (*GetUserTokenReply, error)
	mustEmbedUnimplementedImDigSessionServiceServer()
}

// UnimplementedImDigSessionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedImDigSessionServiceServer struct {
}

func (UnimplementedImDigSessionServiceServer) GetToken(context.Context, *ReqGetTokenMsg) (*GetTokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToken not implemented")
}
func (UnimplementedImDigSessionServiceServer) GetUserToken(context.Context, *ReqGetUserToken) (*GetUserTokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserToken not implemented")
}
func (UnimplementedImDigSessionServiceServer) mustEmbedUnimplementedImDigSessionServiceServer() {}

// UnsafeImDigSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImDigSessionServiceServer will
// result in compilation errors.
type UnsafeImDigSessionServiceServer interface {
	mustEmbedUnimplementedImDigSessionServiceServer()
}

func RegisterImDigSessionServiceServer(s grpc.ServiceRegistrar, srv ImDigSessionServiceServer) {
	s.RegisterService(&ImDigSessionService_ServiceDesc, srv)
}

func _ImDigSessionService_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetTokenMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImDigSessionServiceServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imdigsessionserver.ImDigSessionService/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImDigSessionServiceServer).GetToken(ctx, req.(*ReqGetTokenMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImDigSessionService_GetUserToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetUserToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImDigSessionServiceServer).GetUserToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imdigsessionserver.ImDigSessionService/GetUserToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImDigSessionServiceServer).GetUserToken(ctx, req.(*ReqGetUserToken))
	}
	return interceptor(ctx, in, info, handler)
}

// ImDigSessionService_ServiceDesc is the grpc.ServiceDesc for ImDigSessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImDigSessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "imdigsessionserver.ImDigSessionService",
	HandlerType: (*ImDigSessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetToken",
			Handler:    _ImDigSessionService_GetToken_Handler,
		},
		{
			MethodName: "GetUserToken",
			Handler:    _ImDigSessionService_GetUserToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "imdigsessionserver.proto",
}
